### INITIAL DATA EXPLORATION: FY 15 Conflict

In [1]:
import pandas as pd
import numpy as np

complaint_15 = pd.read_csv('../data/01_raw/fy_15_complaint.csv', skiprows=2)

In [2]:
complaint_15.head()

,Sample,Prod,DateSampled,Grade,DateTested,HSID,Supplier,Gallons,FacilityName,SiteAddress,Test,Units,Method,Result,MinResult,MaxResult,Compliance
0,61915199,Gasoline,3/3/2015 12:00:00 AM,Premium Unleaded,NaN,17247,Tri-star Energy,2798,Hwy 100 Shell,"8456 Highway 100 \r\nnashville, Tn 37221",Antiknock Index,,R+M/2,92.6,87,,
1,61915199,Gasoline,3/3/2015 12:00:00 AM,Premium Unleaded,NaN,17247,Tri-star Energy,2798,Hwy 100 Shell,"8456 Highway 100 \r\nnashville, Tn 37221",API Gravity,,D4052,61.6,,,
2,61915199,Gasoline,3/3/2015 12:00:00 AM,Premium Unleaded,NaN,17247,Tri-star Energy,2798,Hwy 100 Shell,"8456 Highway 100 \r\nnashville, Tn 37221",DIPE,Vol. %,D4815,ND,,,
3,61915199,Gasoline,3/3/2015 12:00:00 AM,Premium Unleaded,NaN,17247,Tri-star Energy,2798,Hwy 100 Shell,"8456 Highway 100 \r\nnashville, Tn 37221",Distillation 10%,Deg. C,D86,42.6,,,Y
4,61915199,Gasoline,3/3/2015 12:00:00 AM,Premium Unleaded,NaN,17247,Tri-star Energy,2798,Hwy 100 Shell,"8456 Highway 100 \r\nnashville, Tn 37221",Distillation 20%,Deg. C,D86,51.2,,,